layout_spectrum: 1
typography_spectrum: 0.7361702
color:
  lightness: 0.6787234
  brandStrength: 0.6553192
  saturation: 0.6893617
  rhythmicContrast: 0.2914894
  brandColors:
    - '#FACFA3'
    - '#1F0C06'
    - '#6F4131'
    - '#9A8888'
    - '#9AADE0'
name: KD Kustoms
